# Generated by Django 4.0 on 2022-08-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auswahl_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='typ2',
            field=models.SmallIntegerField(default=0),
        ),
    ]
