# Generated by Django 4.0 on 2022-09-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_protokoll_typ2'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='einheit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='auswahl',
            name='bis_jg',
            field=models.IntegerField(default=0, verbose_name='bis einschl. Jahrgang:'),
        ),
        migrations.AlterField(
            model_name='auswahl',
            name='bis_stufe',
            field=models.IntegerField(default=0, verbose_name='bis einschl. Stufe:'),
        ),
        migrations.AlterField(
            model_name='schueler',
            name='stufe',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
