# Generated by Django 4.0 on 2022-09-30 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0039_protokoll_einheit_alter_auswahl_bis_jg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachname', models.CharField(max_length=20)),
                ('vorname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('klasse', models.CharField(max_length=10)),
                ('jg', models.PositiveSmallIntegerField(default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
