# Generated by Django 4.0.3 on 2022-10-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_userprofile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
