# Generated by Django 4.0.3 on 2022-10-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schueler',
            name='datum_start',
        ),
        migrations.RemoveField(
            model_name='schueler',
            name='voreinst',
        ),
    ]
