# Generated by Django 4.0.3 on 2022-10-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_schueler_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schueler',
            name='user',
        ),
    ]
