# Generated by Django 4.0.3 on 2022-10-12 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_lerngruppe_lehrer'),
        ('core', '0046_schueler_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokoll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protokolle', to='accounts.schueler', verbose_name='Benutzer'),
        ),
        migrations.AlterField(
            model_name='zaehler',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaehler', to='accounts.schueler', verbose_name='Benutzer'),
        ),
        migrations.DeleteModel(
            name='Schueler',
        ),
    ]
