# Generated by Django 4.0.3 on 2022-10-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_protokoll_halbjahr'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='halbjahr',
            field=models.SmallIntegerField(default=0),
        ),
    ]
