# Generated by Django 4.0.3 on 2022-10-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_protokoll_halbjahr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protokoll',
            old_name='halbjahr',
            new_name='hj',
        ),
        migrations.AddField(
            model_name='protokoll',
            name='sj',
            field=models.SmallIntegerField(default=0),
        ),
    ]
