# Generated by Django 4.0 on 2022-10-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_rename_halbjahr_protokoll_hj_protokoll_sj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hilfe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lfd_nr', models.SmallIntegerField(default=0)),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
