# Generated by Django 4.0 on 2022-10-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_protokoll_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokoll',
            name='hilfe',
            field=models.SmallIntegerField(default=0),
        ),
    ]
