# Generated by Django 4.0 on 2022-10-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_protokoll_werte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hilfe',
            options={'verbose_name_plural': 'Hilfen'},
        ),
        migrations.RenameField(
            model_name='protokoll',
            old_name='werte',
            new_name='parameter',
        ),
    ]
