# Generated by Django 4.0 on 2022-10-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_hilfe_options_rename_werte_protokoll_parameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protokoll',
            name='parameter',
        ),
    ]
