# Generated by Django 4.0 on 2022-10-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_remove_protokoll_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='parameter',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
