# Generated by Django 4.0 on 2022-11-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_protokoll_parameter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zaehler',
            old_name='Extrapunkte',
            new_name='extrapunkte',
        ),
    ]
