# Generated by Django 4.0 on 2022-11-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_rename_extrapunkte_zaehler_extrapunkte'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='frage',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
