# Generated by Django 4.0 on 2022-11-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_protokoll_frage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaehler',
            name='extrapunkte',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
