# Generated by Django 4.0 on 2022-11-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_zaehler_extrapunkte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zaehler',
            name='extrapunkte',
        ),
        migrations.AlterField(
            model_name='zaehler',
            name='richtig',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
