# Generated by Django 4.0 on 2023-01-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_remove_zaehler_extrapunkte_alter_zaehler_richtig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaehler',
            name='bearbeitungszeit',
            field=models.TimeField(default=0),
        ),
    ]
