# Generated by Django 4.0 on 2023-01-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_zaehler_bearbeitungszeit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaehler',
            name='bearbeitungszeit',
            field=models.DurationField(default=0),
        ),
    ]
