# Generated by Django 4.0 on 2023-01-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_zaehler_bearbeitungszeit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaehler',
            name='bearbeitungszeit',
            field=models.FloatField(default=0),
        ),
    ]
