# Generated by Django 4.0 on 2023-01-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_zaehler_bearbeitungszeit'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='end',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Ende'),
        ),
    ]
