# Generated by Django 4.0 on 2023-01-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_protokoll_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaehler',
            name='bearbeitungszeit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
