# Generated by Django 4.0 on 2023-01-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_zaehler_bearbeitungszeit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zaehler',
            old_name='bearbeitungszeit',
            new_name='zeit',
        ),
        migrations.AddField(
            model_name='zaehler',
            name='schnellste',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zaehler',
            name='zeit_summe',
            field=models.FloatField(default=0),
        ),
    ]
