# Generated by Django 4.0 on 2023-01-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_rename_bearbeitungszeit_protokoll_szeit'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategorie',
            name='farbe',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
