# Generated by Django 4.0 on 2023-01-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_kategorie_farbe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorie',
            name='farbe',
            field=models.CharField(choices=[('background-color: #B0E2FF', 'Gruppe A'), ('background-color: #9AFF9A', 'Gruppe B'), ('background-color: #FFFACD', 'Gruppe D'), ('background-color: #FFDEAD', 'Gruppe E'), ('background-color: #FFB5C5', 'Gruppe F')], max_length=25),
        ),
    ]
