# Generated by Django 4.0 on 2023-02-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_kategorie_farbe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hilfe',
            unique_together={('kategorie', 'lfd_nr')},
        ),
    ]
