# Generated by Django 4.0 on 2023-02-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_rename_parameter_protokoll_variable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protokoll',
            old_name='grafik',
            new_name='parameter',
        ),
    ]
