# Generated by Django 4.1.5 on 2023-02-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_rename_grafik_protokoll_parameter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protokoll',
            old_name='pro_text',
            new_name='protext',
        ),
    ]
