# Generated by Django 4.1.5 on 2023-02-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_rename_pro_text_protokoll_protext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protokoll',
            old_name='protext',
            new_name='pro_text',
        ),
    ]
