# Generated by Django 4.1.5 on 2023-02-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_rename_protext_protokoll_pro_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='richtig',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
