# Generated by Django 4.1.5 on 2023-02-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_protokoll_richtig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokoll',
            name='richtig',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
