# Generated by Django 4.1.5 on 2023-02-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_protokoll_falsch'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='abbrechen',
            field=models.BooleanField(default=True),
        ),
    ]
