# Generated by Django 4.1.5 on 2023-02-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_protokoll_lsg_alter_protokoll_hilfe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protokoll',
            old_name='abbrechen',
            new_name='abbr',
        ),
    ]
