# Generated by Django 4.0 on 2023-02-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_rename_abbrechen_protokoll_abbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='help',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='hilfe',
            field=models.SmallIntegerField(default=0),
        ),
    ]
