# Generated by Django 4.0 on 2023-02-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_rename_tries_protokoll_versuche_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zaehler',
            name='abbrechen',
        ),
        migrations.RemoveField(
            model_name='zaehler',
            name='falsch',
        ),
        migrations.RemoveField(
            model_name='zaehler',
            name='hilfe',
        ),
        migrations.RemoveField(
            model_name='zaehler',
            name='loesung',
        ),
        migrations.RemoveField(
            model_name='zaehler',
            name='richtig',
        ),
        migrations.RemoveField(
            model_name='zaehler',
            name='schnellste',
        ),
        migrations.RemoveField(
            model_name='zaehler',
            name='zeit',
        ),
        migrations.RemoveField(
            model_name='zaehler',
            name='zeit_summe',
        ),
    ]
