# Generated by Django 4.0 on 2023-03-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_remove_zaehler_abbrechen_remove_zaehler_falsch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hilfe',
            old_name='lfd_nr',
            new_name='hilfe_id',
        ),
        migrations.AlterUniqueTogether(
            name='hilfe',
            unique_together={('kategorie', 'hilfe_id')},
        ),
    ]
