# Generated by Django 4.1.5 on 2023-03-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_sachaufgabe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hilfe',
            unique_together=set(),
        ),
    ]
