# Generated by Django 3.2.17 on 2023-04-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_hilfe_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sachaufgabe',
            name='ergebnis',
        ),
        migrations.AddField(
            model_name='sachaufgabe',
            name='anmerkung',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sachaufgabe',
            name='variable',
            field=models.JSONField(default=[], help_text="z.B.:{'a': [5, 5.5, 6, 6.5, 7], 'b': [[2, 'zwei'], [4, 'vier']]}"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sachaufgabe',
            name='loesung',
            field=models.CharField(help_text='z.B.: {c}*{a:.2f}+{d}*{b:.2f}={:.2f}', max_length=50),
        ),
    ]
