# Generated by Django 4.0 on 2023-07-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_auto_20230409_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protokoll',
            name='individuell',
        ),
    ]
