# Generated by Django 4.0 on 2023-07-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_remove_protokoll_individuell'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaehler',
            name='fehler_zaehler',
            field=models.SmallIntegerField(default=0),
        ),
    ]
