# Generated by Django 4.0 on 2023-08-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_zaehler_fehler_zaehler'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaehler',
            name='abbr_zaehler',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zaehler',
            name='hilfe_zaehler',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zaehler',
            name='lsg_zaehler',
            field=models.SmallIntegerField(default=0),
        ),
    ]
