# Generated by Django 4.0 on 2023-08-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_zaehler_abbr_zaehler_zaehler_hilfe_zaehler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaehler',
            name='hj',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zaehler',
            name='sj',
            field=models.SmallIntegerField(default=0),
        ),
    ]
