# Generated by Django 4.0 on 2023-08-11 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_zaehler_hj_zaehler_sj'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaehler',
            name='letzte',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2022, 8, 1), verbose_name='Letzte Bearbeitung'),
            preserve_default=False,
        ),
    ]
