# Generated by Django 4.0 on 2023-08-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_zaehler_letzte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorie',
            name='eof',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Eingaben ohne Fehler'),
        ),
    ]
