# Generated by Django 4.0 on 2024-01-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_lerngruppe_aufgaben_pro_woche_lerngruppe_jg'),
        ('core', '0098_alter_kategorie_eof'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zaehler',
            unique_together={('kategorie', 'user')},
        ),
    ]
