# Generated by Django 4.0 on 2024-01-15 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_alter_zaehler_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaehler',
            name='fehler_ab',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2023, 8, 1)),
            preserve_default=False,
        ),
    ]
