# Generated by Django 4.0 on 2024-02-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_zaehler_fehler_ab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokoll',
            name='titel',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
