# Generated by Django 4.0 on 2022-10-01 10:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schueler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachname', models.CharField(max_length=30)),
                ('vorname', models.CharField(max_length=30)),
                ('klasse', models.CharField(max_length=10)),
                ('jg', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('kurs', models.CharField(choices=[('Y', 'Gymnasium'), ('R', 'Realschule'), ('H', 'Hauptschule'), ('E', 'E-Kurs'), ('G', 'G-Kurs'), ('A', 'A-Kurs'), ('B', 'B-Kurs'), ('C', 'C-Kurs'), ('i', 'Förderschüler')], default='E', max_length=1)),
                ('datum_start', models.DateField(auto_now_add=True, verbose_name='Startdatum')),
                ('stufe', models.PositiveSmallIntegerField(default=5)),
                ('halbjahr', models.PositiveSmallIntegerField(default=0)),
                ('voreinst', models.IntegerField(default=1, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'Schüler',
                'verbose_name_plural': 'Schüler',
            },
        ),
    ]
