# Generated by Django 4.0 on 2022-10-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schueler',
            name='datum_start',
        ),
        migrations.RemoveField(
            model_name='schueler',
            name='stufe',
        ),
        migrations.RemoveField(
            model_name='schueler',
            name='voreinst',
        ),
    ]
