# Generated by Django 4.0 on 2022-10-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_schueler_datum_start_remove_schueler_stufe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schueler',
            name='stufe',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
