# Generated by Django 4.0.3 on 2022-10-11 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_schueler_stufe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schueler',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schueler', to=settings.AUTH_USER_MODEL),
        ),
    ]
