# Generated by Django 4.0.3 on 2022-10-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_schueler_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('postleitzahl', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Schule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ort')),
            ],
        ),
        migrations.CreateModel(
            name='Lehrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachname', models.CharField(max_length=30)),
                ('vorname', models.CharField(max_length=30)),
                ('schule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.schule')),
            ],
        ),
    ]
