# Generated by Django 4.0.3 on 2022-10-11 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_ort_schule_lehrer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lehrer',
            options={'verbose_name_plural': 'Lehrer'},
        ),
        migrations.AlterModelOptions(
            name='ort',
            options={'verbose_name_plural': 'Orte'},
        ),
        migrations.AlterModelOptions(
            name='schule',
            options={'verbose_name_plural': 'Schulen'},
        ),
        migrations.CreateModel(
            name='Lerngruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('lehrer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.schule')),
            ],
            options={
                'verbose_name_plural': 'Lehrngruppen',
            },
        ),
    ]
