# Generated by Django 4.0.3 on 2022-10-11 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_lehrer_options_alter_ort_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schueler',
            name='lerngruppe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.lerngruppe'),
        ),
        migrations.AlterField(
            model_name='lehrer',
            name='schule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.schule'),
        ),
        migrations.AlterField(
            model_name='schule',
            name='ort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ort'),
        ),
    ]
