# Generated by Django 4.0.3 on 2022-10-12 13:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_lerngruppe_lehrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lehrer',
            name='jg',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lehrer',
            name='kurs',
            field=models.CharField(choices=[('Y', 'Gymnasium'), ('R', 'Realschule'), ('H', 'Hauptschule'), ('E', 'E-Kurs'), ('G', 'G-Kurs'), ('A', 'A-Kurs'), ('B', 'B-Kurs'), ('C', 'C-Kurs'), ('i', 'Förderschüler')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='lehrer',
            name='stufe',
            field=models.PositiveSmallIntegerField(default=51),
        ),
        migrations.AlterField(
            model_name='schueler',
            name='lerngruppe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.lerngruppe'),
        ),
    ]
