# Generated by Django 4.0.3 on 2022-10-12 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_lehrer_jg_lehrer_kurs_lehrer_stufe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lehrer',
            name='jg',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
