# Generated by Django 4.0.3 on 2022-10-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_schueler_halbjahr_schueler_hj_schueler_sj'),
    ]

    operations = [
        migrations.AddField(
            model_name='schueler',
            name='voreinst',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
