# Generated by Django 4.0 on 2022-11-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_schueler_voreinst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schueler',
            name='voreinst',
            field=models.IntegerField(default=1),
        ),
    ]
