# Generated by Django 4.0 on 2022-12-26 15:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_postleitzahl_ort_plz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lehrer',
            name='kurs',
            field=models.CharField(choices=[('Y', 'Gymnasium'), ('R', 'Realschule'), ('H', 'Hauptschule'), ('S', 'Grundschule'), ('E', 'E-Kurs'), ('G', 'G-Kurs'), ('A', 'A-Kurs'), ('B', 'B-Kurs'), ('C', 'C-Kurs'), ('i', 'Förderschüler')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='lerngruppe',
            name='lehrer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gruppe', to='accounts.lehrer'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='plz',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='schueler',
            name='jg',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='schueler',
            name='kurs',
            field=models.CharField(choices=[('Y', 'Gymnasium'), ('R', 'Realschule'), ('H', 'Hauptschule'), ('S', 'Grundschule'), ('E', 'E-Kurs'), ('G', 'G-Kurs'), ('A', 'A-Kurs'), ('B', 'B-Kurs'), ('C', 'C-Kurs'), ('i', 'Förderschüler')], default='E', max_length=1),
        ),
    ]
