# Generated by Django 4.0 on 2022-12-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0062_remove_zaehler_extrapunkte_alter_zaehler_richtig'),
        ('accounts', '0019_rename_name_schule_schulname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schueler',
            new_name='Profil',
        ),
    ]
