# Generated by Django 4.0 on 2022-12-27 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0020_rename_schueler_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lerngruppe',
            name='lehrer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gruppe', to='auth.user'),
        ),
        migrations.DeleteModel(
            name='Lehrer',
        ),
    ]
