# Generated by Django 4.0 on 2022-12-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_lerngruppe_lehrer_delete_lehrer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='lerngruppe',
        ),
        migrations.DeleteModel(
            name='Lerngruppe',
        ),
    ]
