# Generated by Django 4.0 on 2022-12-27 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0022_remove_profil_lerngruppe_delete_lerngruppe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lerngruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('lehrer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gruppe', to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Lerngruppen',
            },
        ),
    ]
