# Generated by Django 4.0 on 2022-12-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_profil_lerngruppe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lerngruppe',
            options={},
        ),
    ]
