# Generated by Django 4.0 on 2022-12-27 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_lerngruppe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lerngruppe',
            options={'verbose_name_plural': 'Lerngruppen'},
        ),
        migrations.AddField(
            model_name='profil',
            name='ort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ort'),
        ),
        migrations.AddField(
            model_name='profil',
            name='schule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.schule'),
        ),
    ]
