# Generated by Django 4.0 on 2022-12-28 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0026_alter_lerngruppe_options_profil_ort_profil_schule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.AddField(
            model_name='profil',
            name='katmax',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='auth.user'),
        ),
    ]
