# Generated by Django 4.0 on 2022-12-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_profil_options_profil_katmax_alter_profil_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='katmax',
            new_name='maxkat',
        ),
    ]
