# Generated by Django 4.0 on 2022-12-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_rename_katmax_profil_maxkat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='maxkat',
            new_name='katmax',
        ),
    ]
