# Generated by Django 4.0 on 2023-01-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0030_alter_profil_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterUniqueTogether(
            name='lerngruppe',
            unique_together={('lehrer', 'name')},
        ),
    ]
