# Generated by Django 4.0 on 2023-01-06 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_profil_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='lerngruppe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gruppe', to='accounts.lerngruppe'),
        ),
    ]
