# Generated by Django 4.0 on 2023-01-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_profil_lerngruppe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='lerngruppe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='gruppe', to='accounts.lerngruppe'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='ort',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.ort'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='schule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.schule'),
        ),
    ]
