# Generated by Django 4.0 on 2023-01-08 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_profil_lerngruppe_alter_profil_ort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='lerngruppe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gruppe', to='accounts.lerngruppe'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='ort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ort'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='schule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.schule'),
        ),
    ]
