# Generated by Django 4.0 on 2023-01-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_lerngruppe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='quote',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='richtig',
            field=models.JSONField(null=True),
        ),
    ]
