# Generated by Django 4.0 on 2023-01-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_profil_quote_profil_richtig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='quote',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='profil',
            name='richtig',
            field=models.JSONField(default=[]),
        ),
    ]
