# Generated by Django 4.0 on 2023-01-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_profil_quote_alter_profil_richtig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='quote',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='profil',
            name='richtig',
            field=models.JSONField(),
        ),
    ]
