# Generated by Django 4.0 on 2023-01-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_profil_quote_alter_profil_richtig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='richtig',
        ),
    ]
