# Generated by Django 4.0 on 2023-01-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_remove_profil_quote_remove_profil_richtig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='ort',
        ),
    ]
