# Generated by Django 4.0 on 2023-01-14 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_remove_profil_ort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='schule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.schule'),
        ),
    ]
