# Generated by Django 4.0 on 2023-01-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_profil_schule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='lerngruppe',
            new_name='gruppe',
        ),
    ]
