# Generated by Django 4.0 on 2023-01-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_profil_voreinst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='voreinst',
            field=models.IntegerField(default=1),
        ),
    ]
