# Generated by Django 4.0 on 2023-01-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_alter_profil_gruppe_alter_profil_voreinst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='voreinst',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
