# Generated by Django 4.0.3 on 2023-09-14 11:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_alter_profil_voreinst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='jg',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)]),
        ),
        migrations.AlterField(
            model_name='profil',
            name='schule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schule1', to='accounts.schule'),
        ),
    ]
