# Generated by Django 4.0 on 2023-10-17 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0054_profil_zweite_schule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lerngruppe',
            name='lehrer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='gruppe', to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Geloescht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geloescht', to='auth.user')),
            ],
        ),
    ]
