# Generated by Django 4.0 on 2023-10-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_alter_lerngruppe_lehrer_geloescht'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geloescht',
            options={'verbose_name': 'Gelöscht', 'verbose_name_plural': 'Gelöscht'},
        ),
    ]
