# Generated by Django 4.0 on 2024-01-07 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_alter_geloescht_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lerngruppe',
            name='aufgaben_pro_woche',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lerngruppe',
            name='jg',
            field=models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)]),
            preserve_default=False,
        ),
    ]
