# Generated by Django 4.0 on 2024-01-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_lerngruppe_aufgaben_pro_woche_lerngruppe_jg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='details',
            field=models.BooleanField(default=True),
        ),
    ]
