# Generated by Django 4.0 on 2024-02-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_lerngruppe_ab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='kurs',
            field=models.CharField(choices=[('Y', 'Gymnasium'), ('R', 'Realschule'), ('H', 'Hauptschule'), ('S', 'Grundschule'), ('E', 'E-Kurs'), ('G', 'G-Kurs'), ('A', 'A-Kurs'), ('B', 'B-Kurs'), ('C', 'C-Kurs'), ('i', 'Förderschüler/in')], default='E', max_length=1),
        ),
    ]
